#!/bin/bash
#SBATCH -p ei-medium # partition (queue)
#SBATCH -c 1
#SBATCH --mem 50G # memory pool for all cores
#SBATCH -t 0-01:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-type=end,fail # notifications for job done & fail
#SBATCH --mail-user=camilla.ryan@earlham.ac.uk # send-to address

singularity exec ~/software_workshop/images/tidk.img /opt/miniconda3/bin/tidk search -s 'TTTAGGG' -o Udecumbens_telomere_track -e bedgraph --log -d telomere /hpc-home/ryanc/workarea/scratch/results/022023_data_for_Sanger/yahs_q30_scaffolds_final.fa
